# Data Cleaning and Preprocessing

In this notebook, six datasets are cleaned and preprocessed using a common data cleaning workflow.

The main steps include:

- Loading the datasets
- Understanding the data
- Checking missing values
- Checking duplicate records
- Validating data types
- Handling invalid or unwanted values
- Performing a final data quality check
- Pushing the cleaned datasets into MySQL

In [2]:
import pandas as pd 
import numpy as np

In [3]:
movies_df=pd.read_csv(R"C:\Users\Gokul\Downloads\movies.csv")

In [4]:
movies_df.head()

,movie_id,title,original_language,release_date,runtime,budget,revenue,popularity,vote_average,vote_count,status,overview
0,157336,Interstellar,en,2014-11-05,169,165000000.0,7.466067e+08,73.0452,8.484,40566,Released,The adventures of a group of explorers who mak...
1,27205,Inception,en,2010-07-15,148,160000000.0,8.390306e+08,55.8497,8.400,39727,Released,"Cobb, a skilled thief who commits corporate es..."
2,24428,The Avengers,en,2012-04-25,143,220000000.0,1.518816e+09,72.2515,8.062,38993,Released,When an unexpected enemy emerges and threatens...
3,155,The Dark Knight,en,2008-07-16,152,185000000.0,1.004558e+09,60.5510,8.534,36255,Released,Batman raises the stakes in his war on crime. ...
4,19995,Avatar,en,2009-12-16,162,237000000.0,2.923706e+09,48.1996,7.610,34348,Released,"In the 22nd century, a paraplegic Marine is di..."

In [32]:
movies_df.shape

(2509, 12)

In [33]:
movies_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2509 entries, 0 to 2508
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   movie_id           2509 non-null   int64
 1   title              2509 non-null   str
 2   original_language  2509 non-null   str
 3   release_date       2509 non-null   str
 4   runtime            2509 non-null   int64
 5   budget             2509 non-null   float64
 6   revenue            2509 non-null   float64
 7   popularity         2509 non-null   float64
 8   vote_average       2509 non-null   float64
 9   vote_count         2509 non-null   int64
 10  status             2509 non-null   str
 11  overview           2509 non-null   str
dtypes: float64(4), int64(3), str(5)
memory usage: 989.6 KB

In [34]:
movies_df.isnull().sum()

movie_id             0
title                0
original_language    0
release_date         0
runtime              0
budget               0
revenue              0
popularity           0
vote_average         0
vote_count           0
status               0
overview             0
dtype: int64

In [35]:
movies_df.duplicated().sum()

np.int64(6)

In [36]:
movies_df[movies_df.duplicated(keep=False)]

,movie_id,title,original_language,release_date,runtime,budget,revenue,popularity,vote_average,vote_count,status,overview
56,98,Gladiator,en,2000-05-04,155,103000000.0,465516248.0,38.9610,8.230,21184,Released,"After the death of Emperor Marcus Aurelius, hi..."
902,414,Batman Forever,en,1995-06-16,121,100000000.0,336529144.0,10.8455,5.459,5660,Released,Batman faces off against two foes: the schizop...
1285,72570,The Vow,en,2012-02-05,104,30000000.0,196114570.0,9.7433,7.225,4287,Released,"Happy young married couple Paige and Leo are, ..."
1865,484641,Anna,en,2019-06-19,119,34000000.0,31626978.0,9.9585,6.719,3043,Released,Beneath Anna Poliatova's striking beauty lies ...
2240,8814,Doom,en,2005-10-20,105,60000000.0,58100000.0,6.3758,5.202,2493,Released,A team of space marines known as the Rapid Res...
2319,329833,Zoolander 2,en,2016-02-06,100,50000000.0,56722693.0,6.4048,4.927,2411,Released,Derek and Hansel are modelling again when an o...
2499,329833,Zoolander 2,en,2016-02-06,100,50000000.0,56722693.0,6.4048,4.927,2411,Released,Derek and Hansel are modelling again when an o...
2500,484641,Anna,en,2019-06-19,119,34000000.0,31626978.0,9.9585,6.719,3043,Released,Beneath Anna Poliatova's striking beauty lies ...
2501,414,Batman Forever,en,1995-06-16,121,100000000.0,336529144.0,10.8455,5.459,5660,Released,Batman faces off against two foes: the schizop...
2502,8814,Doom,en,2005-10-20,105,60000000.0,58100000.0,6.3758,5.202,2493,Released,A team of space marines known as the Rapid Res...
2503,72570,The Vow,en,2012-02-05,104,30000000.0,196114570.0,9.7433,7.225,4287,Released,"Happy young married couple Paige and Leo are, ..."
2504,98,Gladiator,en,2000-05-04,155,103000000.0,465516248.0,38.9610,8.230,21184,Released,"After the death of Emperor Marcus Aurelius, hi..."

In [37]:
movies_df=movies_df.drop_duplicates()

In [38]:
movies_df.duplicated().sum()

np.int64(0)

In [39]:
movies_df.dtypes

movie_id               int64
title                    str
original_language        str
release_date             str
runtime                int64
budget               float64
revenue              float64
popularity           float64
vote_average         float64
vote_count             int64
status                   str
overview                 str
dtype: object

In [40]:
movies_df["release_date"]=pd.to_datetime(movies_df["release_date"])

In [11]:
import pymysql

connection = pymysql.connect(
    host="localhost",
    user="root",
    password="root",
    database="TMBD_analytics"
)

print("Database connected successfully!")

Database connected successfully!

In [26]:
cursor = connection.cursor()

In [27]:
create_table_query = """
CREATE TABLE movies (
    movie_id INT PRIMARY KEY,
    title VARCHAR(255),
    original_language VARCHAR(10),
    release_date DATE,
    runtime INT,
    budget FLOAT,
    revenue FLOAT,
    popularity FLOAT,
    vote_average FLOAT,
    vote_count INT,
    status VARCHAR(50),
    overview TEXT
)
"""

cursor.execute(create_table_query)
connection.commit()

print("Movies table created successfully!")

Movies table created successfully!

In [28]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:root@localhost/TMBD_analytics"
)

In [41]:
movies_df.to_sql(
    "movies",
    con=engine,
    if_exists="append",
    index=False
)

print("Movies data inserted successfully!")

Movies data inserted successfully!

In [25]:
cursor.execute("DROP TABLE IF EXISTS movie_genres")
cursor.execute("DROP TABLE IF EXISTS genres")
cursor.execute("DROP TABLE IF EXISTS movies")
connection.commit()

print("Old tables dropped successfully!")

Old tables dropped successfully!

### *Genre csv*

In [3]:
genre_df=pd.read_csv(R"C:\Users\Gokul\Downloads\genres.csv")

In [7]:
genre_df.head(5)

   genre_id genre_name
0        28     Action
1        12  Adventure
2        16  Animation
3        35     Comedy
4        80      Crime

In [5]:
genre_df.shape

(19, 2)

In [8]:
genre_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   genre_id    19 non-null     int64
 1   genre_name  19 non-null     str
dtypes: int64(1), str(1)
memory usage: 573.0 bytes

In [10]:
genre_df.duplicated().sum()

np.int64(0)

In [42]:
cursor = connection.cursor()

create_genres_table = """
CREATE TABLE genres (
    genre_id INT PRIMARY KEY,
    genre_name VARCHAR(50)
)
"""

cursor.execute(create_genres_table)
connection.commit()

print("Genres table created successfully!")

Genres table created successfully!

In [43]:
genre_df.to_sql(
    "genres",
    con=engine,
    if_exists="append",
    index=False
)

print("Genres data inserted successfully!")

Genres data inserted successfully!

### *Movies_genre csv*

In [15]:
mov_genre_df=pd.read_csv(R"C:\Users\Gokul\Downloads\movie_genres.csv")

In [16]:
mov_genre_df.head(5)

   movie_id  genre_id
0    157336        12
1    157336        18
2    157336       878
3     27205        28
4     27205       878

In [17]:
mov_genre_df.shape

(6888, 2)

In [18]:
mov_genre_df.duplicated().sum()

np.int64(10)

In [19]:
mov_genre_df[mov_genre_df.duplicated(keep=False)]

      movie_id  genre_id
1498     57800     10751
2906    411088        18
3257        90        28
4184    456740        27
4607      9334        14
5269      9705        53
5345      9477        12
5728    429300        53
5787      8914        28
5937      1429        80
6878    429300        53
6879      9477        12
6880    411088        18
6881        90        28
6882      9334        14
6883      9705        53
6884      8914        28
6885      1429        80
6886     57800     10751
6887    456740        27

In [20]:
mov_genre_df=mov_genre_df.drop_duplicates()

In [21]:
mov_genre_df.duplicated().sum()

np.int64(0)

In [44]:
cursor = connection.cursor()

create_table = """
CREATE TABLE movie_genres (
    movie_id INT,
    genre_id INT,
    FOREIGN KEY (movie_id) REFERENCES movies(movie_id),
    FOREIGN KEY (genre_id) REFERENCES genres(genre_id)
)
"""


cursor.execute(create_table)
connection.commit()

In [45]:
mov_genre_df.to_sql(
    "movie_genres",
    con=engine,
    if_exists="append",
    index=False
)

print("Movie_genres data inserted successfully!")

Movie_genres data inserted successfully!

### *Cast csv*

In [46]:
cast_df=pd.read_csv(R"C:\Users\Gokul\Downloads\cast.csv")

In [47]:
cast_df.head(10)

,cast_row_id,movie_id,person_id,actor_name,character_name,cast_order
0,1,157336,10297,Matthew McConaughey,Cooper,0
1,2,157336,1813,Anne Hathaway,Brand,1
2,3,157336,3895,Michael Caine,Professor Brand,2
3,4,157336,83002,Jessica Chastain,Murph,3
4,5,157336,1893,Casey Affleck,Tom,4
5,6,157336,8210,Wes Bentley,Doyle,5
6,7,157336,17052,Topher Grace,Getty,6
7,8,157336,851784,Mackenzie Foy,Murph (10 Yrs.),7
8,9,157336,9560,Ellen Burstyn,Murph (older),8
9,10,157336,12074,John Lithgow,Donald,9

In [79]:
cast_df.shape

(24902, 5)

In [49]:
cast_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 24917 entries, 0 to 24916
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   cast_row_id     24917 non-null  int64
 1   movie_id        24917 non-null  int64
 2   person_id       24917 non-null  int64
 3   actor_name      24917 non-null  str
 4   character_name  24906 non-null  str
 5   cast_order      24917 non-null  int64
dtypes: int64(4), str(2)
memory usage: 1.7 MB

In [51]:
cast_df.isnull().sum()

cast_row_id        0
movie_id           0
person_id          0
actor_name         0
character_name    11
cast_order         0
dtype: int64

In [52]:
cast_df[cast_df["character_name"].isnull()]

,cast_row_id,movie_id,person_id,actor_name,character_name,cast_order
14465,14466,97370,1245,Scarlett Johansson,NaN,0
14466,14467,97370,1047644,Jeremy McWilliams,NaN,1
14467,14468,97370,1711557,Lynsey Taylor Mackay,NaN,2
14468,14469,97370,1711559,Dougie McConnell,NaN,3
14469,14470,97370,1711561,Kevin McAlinden,NaN,4
14470,14471,97370,1711616,D. Meade,NaN,5
14471,14472,97370,74841,Andrew Gorman,NaN,6
14472,14473,97370,1711626,Joe Szula,NaN,7
14473,14474,97370,136796,Kryštof Hádek,NaN,8
14474,14475,97370,1711628,Roy Armstrong,NaN,9
20870,20871,5156,1077250,Emma Druetti,NaN,9

In [53]:
cast_df["character_name"]=cast_df["character_name"].fillna("Unknown")

In [54]:
cast_df.duplicated().sum()

np.int64(15)

In [55]:
cast_df=cast_df.drop_duplicates()

In [57]:
cast_df.dtypes

cast_row_id       int64
movie_id          int64
person_id         int64
actor_name          str
character_name      str
cast_order        int64
dtype: object

In [76]:
cursor.execute("""
CREATE TABLE cast (
    cast_row_id INT AUTO_INCREMENT PRIMARY KEY,
    movie_id INT,
    person_id INT,
    actor_name VARCHAR(255),
    character_name VARCHAR(255),
    cast_order INT,
    FOREIGN KEY (movie_id) REFERENCES movies(movie_id)
)
""")

connection.commit()

print("Cast table created successfully!")

Cast table created successfully!

In [ ]:

max_length = cast_df["character_name"].str.len().max()
print(f"Maximum character_name length: {max_length}")


cast_df["character_name"] = cast_df["character_name"].str[:255]

Maximum character_name length: 255

In [ ]:
cursor.execute("DROP TABLE IF EXISTS cast")
connection.commit()

print("Cast table dropped successfully!")

Cast table dropped successfully!

In [78]:
# Now insert the data
cast_df.to_sql(
    "cast",
    con=engine,
    if_exists="append",
    index=False
)

print("Cast data inserted successfully!")

Cast data inserted successfully!

### *Crew csv*

In [80]:
crew_df=pd.read_csv(R"C:\Users\Gokul\Downloads\crew.csv")

In [81]:
crew_df.head()

   crew_row_id  movie_id  person_id        person_name       job department
0            1    157336        527     Jonathan Nolan    Writer    Writing
1            2    157336        525  Christopher Nolan    Writer    Writing
2            3    157336        525  Christopher Nolan  Director  Directing
3            4     27205        525  Christopher Nolan    Writer    Writing
4            5     27205        525  Christopher Nolan  Director  Directing

In [91]:
crew_df.shape

(7289, 6)

In [84]:
crew_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7297 entries, 0 to 7296
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   crew_row_id  7297 non-null   int64
 1   movie_id     7297 non-null   int64
 2   person_id    7297 non-null   int64
 3   person_name  7297 non-null   str
 4   job          7297 non-null   str
 5   department   7297 non-null   str
dtypes: int64(3), str(3)
memory usage: 552.0 KB

In [88]:
crew_df.duplicated().sum()

np.int64(0)

In [87]:
crew_df=crew_df.drop_duplicates()

In [89]:
cursor.execute("""
CREATE TABLE crew (
    crew_row_id INT AUTO_INCREMENT PRIMARY KEY,
    movie_id INT,
    person_id INT,
    person_name VARCHAR(255),
    job VARCHAR(100),
    department VARCHAR(100),
    FOREIGN KEY (movie_id) REFERENCES movies(movie_id)
)
""")

connection.commit()

print("Crew table created successfully!")

Crew table created successfully!

In [90]:
crew_df.to_sql(
    "crew",
    con=engine,
    if_exists="append",
    index=False
)

print("Crew data inserted successfully!")

Crew data inserted successfully!

### *Keyword csv*

In [5]:
keyword_df=pd.read_csv(R"C:\Users\Gokul\Downloads\movie_keywords.csv")

In [6]:
keyword_df.head()

   movie_id  keyword_id                    keyword_name
0    157336        1612                      spacecraft
1    157336        4776               race against time
2    157336         310  artificial intelligence (a.i.)
3    157336        1432                            nasa
4    157336        1521                       time warp

In [7]:
keyword_df.shape

(41701, 3)

In [8]:
keyword_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 41701 entries, 0 to 41700
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   movie_id      41701 non-null  int64
 1   keyword_id    41701 non-null  int64
 2   keyword_name  41701 non-null  str
dtypes: int64(2), str(1)
memory usage: 1.4 MB

In [9]:
keyword_df.duplicated().sum()

np.int64(20)

In [10]:
keyword_df=keyword_df.drop_duplicates()

In [102]:
cursor.execute("""
CREATE TABLE keywords (
    movie_id INT,
    keyword_id INT,
    keyword_name VARCHAR(255),
    FOREIGN KEY (movie_id) REFERENCES movies(movie_id)
)
""")

connection.commit()

In [103]:
keyword_df.to_sql(
    "keywords",
    con=engine,
    if_exists="append",
    index=False
)

print("Keywords data inserted successfully!")

Keywords data inserted successfully!